# Site settings
title: FinanSir
email: hello@finansirapp.com
description: "Your personal finance butler."

baseurl: ""
url: "http://finansirapp.com"

facebook_username: finanSir
twitter_username: finanSir
github_username:  finanSir

# Build settings
markdown: kramdown
