# Site settings
title: FinanSir
email: hello@finansirapp.com
description: > # this means to ignore newlines until "baseurl:"
  FinanSir, your personal finance butler.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://finansirapp.com" # the base hostname & protocol for your site
twitter_username: finanSir
github_username:  finanSir

# Build settings
markdown: kramdown
